### ISSUE TITLE
TITAN-XP上测试图片文件夹 单张2048*1608图片detect函数耗时在60到110毫秒

### ISSUE THREAD

**Issue by CLoudSnowMan** [xiaoxiaotao/faceboxes_plate-#1]
将detect函数分阶段测试耗时如下：
第一阶段图像预处理（包括pad resize操作）耗时在20毫秒 
第二阶段 推理阶段耗时在25毫秒 
第三阶段decode函数 耗时20-70毫秒 速度并不恒定 包括（iou操作和nms操作）
第一阶段和第二阶段都是在cpu上进行的？

**Comment by xiaoxiaotao** [comment]
2k的肯定慢些，我用的都是720p的，可以达到实时，25帧，是cpu
